name: Build "Box64_winlator10"

on:
  workflow_dispatch:

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt install apt-get -y install git cmake make python3 patchelf p7zip gcc-aarch64-linux-gnu -y

    - name: Execute build script
      run: bash ./build.sh

    - name: Release "Box64"
      uses: softprops/action-gh-release@v1
      with:
        body: box64 for winlator10
        tag_name: Box64
        name: Release
        files: |
           $HOME/box64/build/box64
