name: Build "Box64_winlator10"

on:
  workflow_dispatch:

jobs:
  start_building_box64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt -y install git cmake make python3 patchelf p7zip gcc-aarch64-linux-gnu -y
        export PATH=$PATH:/usr/aarch64-linux-gnu/bin
    - name: Execute build script
      run: bash ./build.sh

    - name: Release "Box64"
      uses: softprops/action-gh-release@v1
      with:
        body: box64 build arm64
        tag_name: Box64
        name: Release
        files: |
           /home/runner/work/box64/box64/box64/build/box64_w10.tar.zst
           /home/runner/work/box64/box64/box64/build/box64_w10u.tar.zst
